# https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html#macos-sdk
CONDA_BUILD_SYSROOT:
  # Anaconda uses 1.9 but Ice 3.6.5 includes TLS 1.3 support which requires a more recent SecureTransport
  - /opt/MacOSX10.13.sdk  # [osx]

compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider:
  win: azure
conda_forge_output_validation: true
